# -*- coding: utf-8 -*-
"""opencv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lh8_QzSKlM-mBiAYtR2E-uIvLBp3D3g
"""

import os
from PIL import Image
import numpy as np

base_input_folder = '/content/drive/MyDrive/animal'
base_output_folder = '/content/outputImg'

# Define the subfolders to process
subfolders = ['cat', 'dog']

# Target size for resizing
target_size = (250, 250)

# Create base folders if they don't exist
os.makedirs(base_input_folder, exist_ok=True)
os.makedirs(base_output_folder, exist_ok=True)

print(f"Base input folder: {base_input_folder}")
print(f"Base output folder: {base_output_folder}")
print(f"Subfolders to process: {subfolders}")

for subfolder_name in subfolders:
    input_subfolder_path = os.path.join(base_input_folder, subfolder_name)
    os.makedirs(input_subfolder_path, exist_ok=True)

    if not os.listdir(input_subfolder_path):
        print(f"Input subfolder '{input_subfolder_path}' is empty. Creating a dummy image.")
        dummy_image_path = os.path.join(input_subfolder_path, f'dummy_{subfolder_name}_data.png')
        dummy_image = Image.fromarray(np.uint8(np.random.rand(100, 100, 3) * 255))
        dummy_image.save(dummy_image_path)
        print(f"Created: {dummy_image_path}")
    else:
        print(f"Input subfolder '{input_subfolder_path}' is not empty. Skipping dummy data creation.")

overall_processed_count = 0

for subfolder_name in subfolders:
    input_subfolder_path = os.path.join(base_input_folder, subfolder_name)
    output_subfolder_path = os.path.join(base_output_folder, subfolder_name)

    os.makedirs(output_subfolder_path, exist_ok=True)

    print(f"\nProcessing images in: {input_subfolder_path}")
    processed_in_subfolder = 0
    for filename in os.listdir(input_subfolder_path):
        input_path = os.path.join(input_subfolder_path, filename)
        output_path = os.path.join(output_subfolder_path, filename)

        try:
            with Image.open(input_path) as img:
                resized_img = img.resize(target_size)
                resized_img.save(output_path)
                processed_in_subfolder += 1
                overall_processed_count += 1
                print(f"  Resized '{filename}' and saved to '{output_subfolder_path}'.")
        except Exception as e:
            print(f"  Error processing '{filename}': {e}")
    if processed_in_subfolder == 0:
        print(f"  No image files found or processed in '{input_subfolder_path}'.")

if overall_processed_count == 0:
    print("\nNo image files were processed across all specified subfolders.")
else:
    print(f"\nSuccessfully processed a total of {overall_processed_count} image(s).")

# Optional: Display one of the resized images from the first output subfolder to verify
if overall_processed_count > 0 and len(os.listdir(os.path.join(base_output_folder, subfolders[0]))) > 0:
    print("\nDisplaying one of the resized images:")
    first_output_subfolder = os.path.join(base_output_folder, subfolders[0])
    first_resized_image = os.listdir(first_output_subfolder)[0]
    display(Image.open(os.path.join(first_output_subfolder, first_resized_image)))

# Define augmentation transforms
augmentation_transforms = transforms.Compose([
    transforms.RandomRotation(15),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Create a new output folder for augmented images
base_augmentation_output_folder = '/content/augmented_outputImg'
os.makedirs(base_augmentation_output_folder, exist_ok=True)

num_augmentations_per_image = 5 # Generate 5 augmented versions for each original image

print(f"Starting data augmentation. Augmented images will be saved to: {base_augmentation_output_folder}")

augmented_image_count = 0
for subfolder_name in subfolders:
    input_subfolder_path = os.path.join(base_output_folder, subfolder_name) # Use resized images as base
    output_subfolder_path = os.path.join(base_augmentation_output_folder, subfolder_name)
    os.makedirs(output_subfolder_path, exist_ok=True)

    print(f"  Augmenting images in '{input_subfolder_path}'...")
    for filename in os.listdir(input_subfolder_path):
        input_path = os.path.join(input_subfolder_path, filename)
        try:
            img = Image.open(input_path).convert('RGB')
            for i in range(num_augmentations_per_image):
                augmented_img = augmentation_transforms(img)
                # Convert tensor back to PIL Image for saving, then resize to target_size
                # The ToTensor() transform converts to [C, H, W] and normalizes [0,1].
                # To save as an image, we need to convert back to [H, W, C] and scale [0, 255]
                augmented_img_pil = transforms.ToPILImage()(augmented_img * 0.225 + 0.456) # Denormalize for display/save (approx)
                augmented_img_pil = augmented_img_pil.resize(target_size) # Resize to target size after augmentation

                # Save augmented image with a new name
                new_filename = f"{os.path.splitext(filename)[0]}_aug{i}{os.path.splitext(filename)[1]}"
                output_path = os.path.join(output_subfolder_path, new_filename)
                augmented_img_pil.save(output_path)
                augmented_image_count += 1
        except Exception as e:
            print(f"    Error augmenting '{filename}': {e}")

print(f"Finished data augmentation. Total augmented images created: {augmented_image_count}")

# Transformations for the dataset
# The images are already resized, so we just need to convert to tensor and normalize
dataset_transforms = transforms.Compose([
    transforms.ToTensor(), # Convert PIL Image to PyTorch Tensor
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # Normalize with ImageNet stats
])

# Load the dataset using ImageFolder, now using the augmented output folder
full_dataset = datasets.ImageFolder(root=base_augmentation_output_folder, transform=dataset_transforms)

# Split the dataset into training and testing sets
train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(full_dataset, [train_size, test_size])

# Create DataLoaders
batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

print(f"Total images in dataset: {len(full_dataset)}")
print(f"Training images: {len(train_dataset)}")
print(f"Testing images: {len(test_dataset)}")
print(f"Classes: {full_dataset.classes}")
print(f"Class to index mapping: {full_dataset.class_to_idx}")

# Re-instantiate the model to reset weights for new training
model = SimpleCNN(num_classes=len(full_dataset.classes)).to(device)
print("Model re-instantiated.")

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
num_epochs = 10
print("Criterion, optimizer, and num_epochs re-defined.")

train_losses = []
train_accuracies = []

for epoch in range(num_epochs):
    model.train() # Set the model to training mode
    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0

    for batch_idx, (inputs, labels) in enumerate(train_loader):
        inputs, labels = inputs.to(device), labels.to(device)

        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        # Backward pass and optimize
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Calculate accuracy
        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = 100 * correct_predictions / total_predictions
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_accuracy)

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.2f}%')

print("Finished Training")

model.eval() # Set the model to evaluation mode
correct = 0
total = 0

with torch.no_grad(): # No need to calculate gradients during inference
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f'Accuracy of the network on the {total} test images: {accuracy:.2f}%')

# Plotting training loss and accuracy
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(range(1, num_epochs + 1), train_losses, marker='o')
plt.title('Training Loss per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(range(1, num_epochs + 1), train_accuracies, marker='o', color='green')
plt.title('Training Accuracy per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.grid(True)

plt.tight_layout()
plt.show()

model.eval() # Set the model to evaluation mode

# Get class names from the dataset
class_names = full_dataset.classes

# --- Choose an image to test ---
# You can change this path to any image you want to test
# For demonstration, let's pick an augmented image from the mouse subfolder

# Since we are now using augmented data, let's pick a sample from the augmented output folder.
# We will use the first augmented image from the 'cat' output folder if available.

sample_image_path = None
if os.path.exists(os.path.join(base_augmentation_output_folder, subfolders[0])) and len(os.listdir(os.path.join(base_augmentation_output_folder, subfolders[0]))) > 0:
    sample_image_path = os.path.join(base_augmentation_output_folder, subfolders[0], os.listdir(os.path.join(base_augmentation_output_folder, subfolders[0]))[0])

if sample_image_path:
    print(f"Testing image: {sample_image_path}")

    # Load the image
    image_to_test = Image.open(sample_image_path).convert('RGB')

    # Apply the same transformations as the dataset (ToTensor and Normalize)
    # Note: If your dataset_transforms included resizing, it's already handled because we pick from augmented output
    test_transforms = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    input_tensor = test_transforms(image_to_test)
    input_batch = input_tensor.unsqueeze(0) # Create a mini-batch as expected by the model

    # Move the input to the same device as the model
    input_batch = input_batch.to(device)

    with torch.no_grad():
        output = model(input_batch)

    # Get the predicted class
    _, predicted_idx = torch.max(output, 1)
    predicted_class = class_names[predicted_idx.item()]

    # Display the image and prediction
    plt.imshow(image_to_test)
    plt.title(f"Predicted: {predicted_class}")
    plt.axis('off')
    plt.show()
else:
    print("Skipping single image test due to missing sample image.")

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import torchvision

print(f"PyTorch version: {torch.__version__}")
print(f"Torchvision version: {torchvision.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

# Set device to GPU if available, else CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Transformations for the dataset
# The images are already resized, so we just need to convert to tensor and normalize
dataset_transforms = transforms.Compose([
    transforms.ToTensor(), # Convert PIL Image to PyTorch Tensor
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # Normalize with ImageNet stats
])

# Load the dataset using ImageFolder
# The root is our base_output_folder
full_dataset = datasets.ImageFolder(root=base_output_folder, transform=dataset_transforms)

# Split the dataset into training and testing sets
train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(full_dataset, [train_size, test_size])

# Create DataLoaders
batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

print(f"Total images in dataset: {len(full_dataset)}")
print(f"Training images: {len(train_dataset)}")
print(f"Testing images: {len(test_dataset)}")
print(f"Classes: {full_dataset.classes}")
print(f"Class to index mapping: {full_dataset.class_to_idx}")

class SimpleCNN(nn.Module):
    def __init__(self, num_classes=2):
        super(SimpleCNN, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, padding=1), # Input: 3 channels (RGB), Output: 16 features
            nn.BatchNorm2d(16), # Added Batch Normalization
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2), # Reduces image size by half (e.g., 250 -> 125)

            nn.Conv2d(16, 32, kernel_size=3, padding=1), # Input: 16 features, Output: 32 features
            nn.BatchNorm2d(32), # Added Batch Normalization
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2) # Reduces image size by half (e.g., 125 -> 62)
        )
        # Calculate the size of the feature map after convolutional layers
        # Our input images are 250x250. After two MaxPool2d layers with stride 2,
        # the spatial dimensions become 250 / 2 / 2 = 62.5, which will be 62 due to floor operation.
        # So, the size is 32 features * 62 * 62.
        self.classifier = nn.Sequential(
            nn.Flatten(), # Flatten the 3D feature map to a 1D vector
            nn.Linear(32 * 62 * 62, 128), # First fully connected layer
            nn.ReLU(),
            nn.Dropout(0.5), # Dropout for regularization
            nn.Linear(128, num_classes) # Output layer with 2 classes (mouse, keyboard)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

# Instantiate the model and move it to the device (GPU/CPU)
model = SimpleCNN(num_classes=len(full_dataset.classes)).to(device)
print(model)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
num_epochs = 10

train_losses = []
train_accuracies = []

for epoch in range(num_epochs):
    model.train() # Set the model to training mode
    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0

    for batch_idx, (inputs, labels) in enumerate(train_loader):
        inputs, labels = inputs.to(device), labels.to(device)

        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        # Backward pass and optimize
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Calculate accuracy
        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = 100 * correct_predictions / total_predictions
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_accuracy)

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.2f}%')

print("Finished Training")

model.eval() # Set the model to evaluation mode
correct = 0
total = 0

with torch.no_grad(): # No need to calculate gradients during inference
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f'Accuracy of the network on the {total} test images: {accuracy:.2f}%')

# Plotting training loss and accuracy
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(range(1, num_epochs + 1), train_losses, marker='o')
plt.title('Training Loss per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(range(1, num_epochs + 1), train_accuracies, marker='o', color='green')
plt.title('Training Accuracy per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.grid(True)

plt.tight_layout()
plt.show()

model.eval() # Set the model to evaluation mode

# Get class names from the dataset
class_names = full_dataset.classes

# --- Choose an image to test ---
# You can change this path to any image you want to test
# For demonstration, let's pick an augmented image from the mouse subfolder

# Since the previous sample path did not exist, let's try to pick a sample from the output folder.
# We will use the first image from the 'cat' output folder if available.

sample_image_path = None
if os.path.exists(os.path.join(base_output_folder, subfolders[0])) and len(os.listdir(os.path.join(base_output_folder, subfolders[0]))) > 0:
    sample_image_path = os.path.join(base_output_folder, subfolders[0], os.listdir(os.path.join(base_output_folder, subfolders[0]))[0])

if sample_image_path:
    print(f"Testing image: {sample_image_path}")

    # Load the image
    image_to_test = Image.open(sample_image_path).convert('RGB')

    # Apply the same transformations as the dataset (ToTensor and Normalize)
    test_transforms = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    input_tensor = test_transforms(image_to_test)
    input_batch = input_tensor.unsqueeze(0) # Create a mini-batch as expected by the model

    # Move the input to the same device as the model
    input_batch = input_batch.to(device)

    with torch.no_grad():
        output = model(input_batch)

    # Get the predicted class
    _, predicted_idx = torch.max(output, 1)
    predicted_class = class_names[predicted_idx.item()]

    # Display the image and prediction
    plt.imshow(image_to_test)
    plt.title(f"Predicted: {predicted_class}")
    plt.axis('off')
    plt.show()
else:
    print("Skipping single image test due to missing sample image.")

model_save_path = 'simple_cnn_model.pth'
torch.save(model.state_dict(), model_save_path)
print(f"Model saved to {model_save_path}")

requirements_content = """
torch
torchvision
pillow
streamlit
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements_content)

print("requirements.txt created.")
print("\nContent of requirements.txt:\n")
print(requirements_content)

app_py_content = '''
import streamlit as st
import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image
import os

# Define the same CNN architecture as in training
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=2):
        super(SimpleCNN, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            # The input features for the linear layer depend on the image size
            # Our images were 250x250, so after two MaxPool2d layers (stride 2),
            # the size becomes 250 / 4 = 62.5, which is floored to 62.
            nn.Linear(32 * 62 * 62, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

# Configuration
IMAGE_SIZE = (250, 250)
CLASS_NAMES = ['keyboard', 'mouse'] # Make sure this matches your dataset classes
MODEL_PATH = 'simple_cnn_model.pth' # Path to your saved model

# Load the trained model
@st.cache_resource
def load_model():
    model = SimpleCNN(num_classes=len(CLASS_NAMES))
    model.load_state_dict(torch.load(MODEL_PATH, map_location=torch.device('cpu')))
    model.eval()
    return model

# Image transformations (must match training transformations)
def get_transforms():
    return transforms.Compose([
        transforms.Resize(IMAGE_SIZE),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

# Predict function
def predict(image, model, transform):
    image = image.convert('RGB')
    image_tensor = transform(image).unsqueeze(0) # Add batch dimension

    with torch.no_grad():
        output = model(image_tensor)
        probabilities = torch.softmax(output, dim=1)
        _, predicted_idx = torch.max(output, 1)
        return CLASS_NAMES[predicted_idx.item()], probabilities[0][predicted_idx.item()].item()

# Streamlit app layout
st.title("Image Classifier: Keyboard vs. Mouse")
st.write("Upload an image and let the model predict if it's a keyboard or a mouse.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image.', use_column_width=True)
    st.write("")
    st.write("Classifying...")

    # Load model and transforms
    model = load_model()
    transform = get_transforms()

    # Make prediction
    predicted_class, confidence = predict(image, model, transform)

    st.success(f"Prediction: {predicted_class} (Confidence: {confidence:.2f})")

# How to run the app:
st.markdown("""
To run this Streamlit app locally, save the above content as `app.py` in the same directory as `simple_cnn_model.pth` and `requirements.txt`.
Then, open your terminal in that directory and run:
```bash
streamlit run app.py
```
"""
)
'''

with open('app.py', 'w') as f:
    f.write(app_py_content)

print("app.py created.")
print("\nContent of app.py:\n")
print(app_py_content)

"""## Resources

### Configuration:
- **Base Input Folder:** `/content/drive/MyDrive/animal`
- **Base Output Folder:** `/content/outputImg`
- **Subfolders Processed:** `['cat', 'dog']`
- **Target Image Size:** `(250, 250)`
- **Batch Size:** `32`

### Dataset Information:
- **Total Images in Dataset:** `4`
- **Training Images:** `3`
- **Testing Images:** `1`
- **Classes:** `['cat', 'dog']`
- **Class to Index Mapping:** `{'cat': 0, 'dog': 1}`
"""